name: rapidlie
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+6

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl:
  provider: ^6.1.2
  flutter_screenutil: ^5.9.0
  permission_handler: ^12.0.1
  intl_phone_number_input: ^0.7.0+2
  flutter_svg: ^2.0.9
  country_list_pick: ^1.0.1+6
  cached_network_image: ^3.3.1
  expandable_page_view: ^1.0.17
  table_calendar: ^3.0.8
  image_picker: ^1.1.2
  url_launcher: ^6.1.9
  connectivity_plus: ^6.1.1
  pinput: ^5.0.0
  grouped_list: ^6.0.0
  get_it:
  http:
  shared_preferences:
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  dio: ^5.6.0
  crypto: ^3.0.6
  google_fonts: ^6.3.0
  google_maps_flutter: ^2.9.0
  flutter_dotenv: ^6.0.0
  image_stack: ^2.1.1
  libphonenumber_plugin:
  flutter_contacts: ^1.1.9+2
  geocoding: ^4.0.0
  geolocator: 14.0.2
  flutter_google_places_sdk: ^0.4.2+1
  package_info_plus: ^8.1.2
  go_router: ^15.1.1
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  webview_flutter: ^4.10.0
  country_code_picker: ^3.4.0
  flutter_local_notifications: ^19.4.2
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/flockr_icon.png" 
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/flockr_icon_new.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  retrofit_generator:
  floor_generator:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.1

dependency_overrides: 
   geolocator_android: 4.6.1

flutter:
  generate: true

  uses-material-design: true

  assets: 
    - .env
    - assets/icons/
    - assets/images/
  
